import { EstadoBooleano } from "../EstadoBooleano/Estado";
import { Coleccion } from "../Iterador/Coleccion";
import { ColeccionBooleana } from "../Iterador/ColeccionBooleana";
import { Iterador } from "../Iterador/Iterador";
import { IteradorBooleano } from "../Iterador/IteradorBooleano";
import { ContextoBooleano } from "../EstadoBooleano/Contexto";
/*var coleccion:Coleccion=new ColeccionBooleana();
coleccion.crearIterador();
var iterador:Iterador=coleccion.getIterador();
iterador.buscarNombre("Verdad");
var test:EstadoBooleano=iterador.buscarNombre("Mentira");
var test1:EstadoBooleano=iterador.buscarNombre("Mentira");
console.log(test===test1);
console.log(iterador);
console.log(coleccion);
coleccion.printArray();*/
var contexto:ContextoBooleano=new ContextoBooleano();
console.log(contexto.getEstado());
contexto.cambioDeEstado();
console.log(contexto.getEstado());
contexto.cambioDeEstado();
console.log(contexto.getEstado());